# -*- coding: utf-8 -*-
"""week4 internship task Ai/ML devsphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGGoJHWY1r1QCodQk3Ovskf-c_zGDCWO
"""



"""## **Ai Task**"""

import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

print("======================================")
print("   AI WEEK 4 - NEURAL NETWORK")
print("======================================")

# Load dataset
df = pd.read_csv("student_scores.csv")

print("\n========== DATASET ==========")
print(df)

# Input feature and target
X = df[["StudyHours"]]
y = df["ExamScore"]

# Scale input data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Create Neural Network model
model = MLPRegressor(
    hidden_layer_sizes=(10,),
    activation="relu",
    solver="lbfgs",
    max_iter=5000,
    random_state=42
)

# Train model
model.fit(X_scaled, y)

print("\n========== MODEL TRAINING ==========")
print("Neural Network trained successfully!")

# New data for prediction
test_data = pd.DataFrame({
    "StudyHours": [4, 6, 8]
})

# Scale test data
test_scaled = scaler.transform(test_data)

# Make predictions
predictions = model.predict(test_scaled)

print("\n========== PREDICTIONS ==========")

for hours, score in zip(test_data["StudyHours"], predictions):
    print(
        f"Study Hours: {hours} -> "
        f"Predicted Exam Score: {score:.2f}"
    )

print("\n========== NETWORK INFORMATION ==========")
print("Input Layer: 1 feature")
print("Hidden Layer: 10 neurons")
print("Activation Function: ReLU")
print("Output: Predicted Exam Score")

print("\n======================================")
print("   BASIC NEURAL NETWORK COMPLETED")
print("======================================")

"""# **ML Task**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

print("======================================")
print("   ML WEEK 4 - CLASSIFICATION")
print("======================================")

# Load classification dataset
df = pd.read_csv("student_classification.csv")

print("\n========== DATASET ==========")
print(df)

# Features and target
X = df[["StudyHours", "Attendance"]]
y = df["Passed"]

# Split dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# Create classification model
model = LogisticRegression()

# Train model
model.fit(X_train, y_train)

print("\n========== MODEL TRAINING ==========")
print("Logistic Regression model trained successfully!")

# Predict test data
y_pred = model.predict(X_test)

print("\n========== PREDICTIONS ==========")
print("Actual values:   ", list(y_test))
print("Predicted values:", list(y_pred))

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\n========== ACCURACY ==========")
print(f"Accuracy Score: {accuracy * 100:.2f}%")

# Predict new students
new_students = pd.DataFrame({
    "StudyHours": [3, 6, 9],
    "Attendance": [60, 80, 90]
})

new_predictions = model.predict(new_students)

print("\n========== NEW PREDICTIONS ==========")

for i, prediction in enumerate(new_predictions):
    result = "Pass" if prediction == 1 else "Fail"

    print(
        f"Student {i + 1}: "
        f"Study Hours = {new_students.iloc[i]['StudyHours']}, "
        f"Attendance = {new_students.iloc[i]['Attendance']}% "
        f"-> Prediction: {result}"
    )

print("\n======================================")
print("   WORKING CLASSIFICATION MODEL")
print("======================================")